### ISSUE TITLE
Add a code check tool at server initialization

### ISSUE THREAD

**Issue by kenashkov** [AzonMedia/guzaba2#10]
This tool should check for:
- "==" - comparison should always be done with "==="
- all files must have declare(strict_types=1);
- more to be added in future...

**Comment by kenashkov** [comment]
Work in branch V_0_0_6.
Add a new public stsatic method in Guzaba2\Kernel\ClassDeclarationValidation::check_source()

**Comment by deooo1** [comment]
Added in master
